const kids = [
    {
        id: "K1",
        imgurl: "https://i.ebayimg.com/images/g/VNAAAOSw8BZk0LjE/s-l960.jpg",
        title: "Amazon cloths",
        rating: 0,
        oprice: 900,
        disprice: 599,
        quantity: 0,
        color: [
            { colorid: 'pink', clrimg: "https://i.ebayimg.com/images/g/93wAAOSwcV5k7HEM/s-l960.jpg" },
            { colorid: 'blue', clrimg: "https://i.ebayimg.com/images/g/sJ0AAOSwsOVkuj9B/s-l960.jpg" },
            { colorid: 'red', clrimg: "https://i.ebayimg.com/images/g/gYMAAOSwAkVfiOwe/s-l960.jpg" },
        ],
    },
    {
        id: "K2",
        imgurl: "https://i.ebayimg.com/images/g/jeMAAOSwDW1iqCpw/s-l960.jpg",
        title: "Flipkart cloths",
        oprice: 900,
        rating: 0,
        disprice: 599,
        quantity: 0,
        color: [
            { colorid: 'red', clrimg: "https://i.ebayimg.com/images/g/Lm0AAOSwVmViqCpn/s-l960.png" },
            { colorid: 'pink', clrimg: "https://i.ebayimg.com/images/g/b5UAAOSwhXNiqCp5/s-l960.jpg" },
            { colorid: 'white', clrimg: "https://i.ebayimg.com/images/g/O0AAAOSw4A1iqCp8/s-l960.jpg" },
        ],
    },
    {
        id: "K3",
        imgurl: "https://i.ebayimg.com/images/g/FB0AAOSwVJBijy7I/s-l960.jpg",
        title: "Myntra cloths",
        oprice: 900,
        rating: 0,
        disprice: 599,
        quantity: 0,
        color: [
            { colorid: 'green', clrimg: "https://i.ebayimg.com/images/g/mI8AAOSw6ANijy7G/s-l1600.jpg" },
            { colorid: 'red', clrimg: "https://i.ebayimg.com/images/g/80cAAOSwPN5ijy7e/s-l960.jpg" },
            { colorid: 'blue', clrimg: "https://i.ebayimg.com/images/g/fdMAAOSwMI5ijy6~/s-l960.jpg" },
        ],
    },
    {
        id: "K4",
        imgurl: "https://m.media-amazon.com/images/G/31/img2020/img21/kids/Winterflip2023/Baby/Brands/Hopscotch_2._SX846_QL85_FMpng_.png",
        rating: 0,
        title: "Myntra cloths",
        oprice: 900,
        disprice: 599,
        quantity: 0,
        color: [
            { colorid: 'grey', clrimg: "https://m.media-amazon.com/images/I/51-ISImNTEL._AC_UL480_FMwebp_QL65_.jpg" },
            { colorid: 'navy blue', clrimg: "https://m.media-amazon.com/images/I/511wuGpCVjL._AC_UL480_FMwebp_QL65_.jpg" },
            { colorid: 'blue', clrimg: "https://m.media-amazon.com/images/I/61Eyv-MHHGL._AC_UL480_FMwebp_QL65_.jpg" },
        ],
    },
    {
        id: "K5",
        imgurl: "https://m.media-amazon.com/images/I/61OA7Xt45iL._SY741_.jpg",
        title: "Amazon cloths",
        oprice: 900,
        rating: 0,
        disprice: 599,
        quantity: 0,
        color: [
            { colorid: 'pink', clrimg: "https://m.media-amazon.com/images/I/614bSsSLQFL._SY741_.jpg" },
            { colorid: 'oragne', clrimg: "https://m.media-amazon.com/images/I/61obnlln5IL._SY741_.jpg" },
            { colorid: 'voilet', clrimg: "https://m.media-amazon.com/images/I/61fXgRWRz9L._SY741_.jpg" },
        ],
    },
    {
        id: "K6",
        imgurl: "https://m.media-amazon.com/images/G/31/img2020/img21/kids/Winterflip2023/Baby/Brands/Greendigo_6._SX846_QL85_FMpng_.png",
        title: "flipkart cloths",
        oprice: 900,
        rating: 0,
        disprice: 599,
        quantity: 0,
        color: [
            { colorid: 'green', clrimg: "https://m.media-amazon.com/images/I/61tBtWtlAYL._AC_UL480_FMwebp_QL65_.jpg" },
            { colorid: 'blue', clrimg: "https://m.media-amazon.com/images/I/71EJxibSdYL._AC_UL480_FMwebp_QL65_.jpg" },
            { colorid: 'white', clrimg: "https://m.media-amazon.com/images/I/71e9UrUh5nL._AC_UL480_FMwebp_QL65_.jpg" },
        ],
    },
    {
        id: "K7",
        imgurl: "https://m.media-amazon.com/images/I/61fSKTW9fVL._SX679_.jpg",
        title: "shopsy cloths",
        oprice: 900,
        rating: 0,
        disprice: 599,
        quantity: 0,
        color: [
            { colorid: 'red', clrimg: "https://m.media-amazon.com/images/I/817mw55PVlL._SX679_.jpg" },
            { colorid: 'yellow', clrimg: "https://m.media-amazon.com/images/I/81g6Q83tZlL._SY741_.jpg" },
            { colorid: 'blue', clrimg: "https://m.media-amazon.com/images/I/81rZTR8N2QL._SY741_.jpg" },
        ],
    },
    {
        id: "K8",
        imgurl: "https://m.media-amazon.com/images/I/61o7VvRITEL._SY741_.jpg",
        title: "shopsy cloths",
        oprice: 900,
        rating: 0,
        disprice: 599,
        quantity: 0,
        color: [
            { colorid: 'pink', clrimg: "https://m.media-amazon.com/images/I/61WcXn-h5TL._SY741_.jpg" },
            { colorid: 'blue', clrimg: "https://m.media-amazon.com/images/I/61FxTZxAK6L._SY741_.jpg" },
            { colorid: 'orange', clrimg: "https://m.media-amazon.com/images/I/61RfKDCKj0L._SY741_.jpg" },
        ],
    },
]

export default kids;
